version: '3'
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MiningDB-Database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Bv825lGeeZw8
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"